import { Chessboard } from "chessboard.slint";

// Setting up custom callbacks in order to be able to set them in the main function
export global FenUtils {
    pure callback get_piece_from_fen(string, int) -> string; // (fen, cellIndex where a1 == 0)
    pure callback is_white_turn_in_fen(string) -> bool; // (fen)
}

export component App inherits Window {
    min-width: 100px;
    min-height: 100px;
    preferred-width: 200px;
    preferred-height: 200px;
    background: lemonchiffon;

    pure callback get_current_position() -> string;

    HorizontalLayout {
        x: min(root.width, root.height) * 0.05;
        y: min(root.width, root.height) * 0.05;
        spacing: min(root.width, root.height) * 0.1;
        Chessboard {
            size: min(root.width, root.height) * 0.4;
            positionFen: get-current-position();
            get_piece_from_fen(fen, cell_index) => {
                FenUtils.get_piece_from_fen(fen, cell_index);
            }
            is_white_turn_in_fen(fen) => {
                FenUtils.is_white_turn_in_fen(fen);
            }
        }
    
        Chessboard {
            size: min(root.width, root.height) * 0.4;
            reversed: true;
            positionFen: get-current-position();
            get_piece_from_fen(fen, cell_index) => {
                FenUtils.get_piece_from_fen(fen, cell_index);
            }
            is_white_turn_in_fen(fen) => {
                FenUtils.is_white_turn_in_fen(fen);
            }
        }
    }
}